### ISSUE TITLE
the musket can be fired infinitely,

### ISSUE THREAD

**Issue by cocojiang39** [ewewukek/mc-musketmod#21]
Loading when entering and exiting the gate of hell, the musket can be fired infinitely, which is too unbalanced

**Comment by Inqie** [comment]
It seems that changing dimension while loading the musket causes the NBT to get stuck with a "loadingStage" of 4 and "loaded" of 1 (true). This of course means that every shot takes a fraction of a second to load and fire. It is an easily replicable exploit. 
I recommend fixing this be a priority since it results in such an overpowered weapon.
